name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for participating in this repository and your feedback is very important to me.'' first issue'
        pr-message: 'Your contribution is highly appreciated, thank you for your Pull Request, I will look at shortly and be in touch with you.❤'' first pr'
